# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_cards
    volumes:
       - './postgres:/var/lib/postgresql/data'
    ports:
      - "5431:5432"